"use client";

import { useEffect, useMemo, useState } from "react";

type Phase="lobby"|"observe"|"decide"|"results";
type Proposal={participant:string;profile:string;choice:string;label:string;reason:string;deltas:{cost:number;time:number;quality:number;human:number;risk:number}};
type Participant={name:string;profile:string};
type Session={mission:string;phase:Phase;participants:Participant[];proposals:Proposal[];createdAt:string};
type View="home"|"catalog"|"facilitator"|"join"|"participant";

const missions=[
  {id:"service",title:"Atendimento digital",duration:"75 minutos",summary:"Uma operação multiagente ganhou velocidade e reduziu custo. Nos últimos 90 dias, reaberturas e transferências para pessoas começaram a crescer.",concepts:"Orquestração, escolha de modelos, ferramentas, filas humanas, qualidade e custo.",metrics:[82,14.8,6.4,28,312],agents:[
    {name:"Triagem",job:"Entende o pedido e encaminha o trabalho.",provider:"Google",model:"Gemini · API externa",tools:"Cadastro e histórico de contatos",limit:"Classifica; não responde ao cliente."},
    {name:"Conhecimento",job:"Localiza políticas e informações necessárias.",provider:"OpenAI",model:"GPT · endpoint privado",tools:"Busca na base de conhecimento",limit:"Reúne evidências; não cria políticas."},
    {name:"Resolução",job:"Prepara uma solução usando as evidências encontradas.",provider:"Anthropic",model:"Claude · API externa",tools:"CRM e catálogo de procedimentos",limit:"Recomenda e redige; não concede exceções."},
    {name:"Qualidade",job:"Verifica evidência, coerência e necessidade de revisão humana.",provider:"Modelo interno",model:"Classificador próprio",tools:"Políticas e avaliações históricas",limit:"Aprova automação ou escala; não atende."},
  ]},
  {id:"marketing",title:"Marketing e crescimento",duration:"90 minutos",summary:"Agentes planejam, produzem e distribuem campanhas. A conversão cresceu, mas custo, repetição e risco de comunicação inadequada também aumentaram.",concepts:"Segmentação, conteúdo, orçamento, privacidade, aprovação e autonomia.",metrics:[76,18.2,7.1,21,428],agents:[]},
  {id:"procurement",title:"Compras e contratos",duration:"90 minutos",summary:"Agentes pesquisam fornecedores, comparam propostas e analisam contratos. O ciclo encurtou, enquanto exceções e dependência de fornecedores cresceram.",concepts:"Documentos, recuperação de informação, alçadas, rastreabilidade e dados sensíveis.",metrics:[69,24.6,8.8,34,506],agents:[]},
] as const;

const profiles=["CEO","Finanças","Marketing","Operações","Tecnologia","Compliance","Dados e IA","Segurança","Experiência do cliente","Gestão de pessoas"];

const decisions:Record<string,{question:string;context:string;choices:Array<{id:string;label:string;detail:string;deltas:Proposal["deltas"]}>}>={
  "CEO":{question:"Qual equilíbrio deve orientar o próximo período?",context:"Automação cresceu, mas qualidade e carga humana se deterioraram.",choices:[
    {id:"ceo-growth",label:"Preservar velocidade",detail:"Manter a meta de automação e aceitar maior exposição.",deltas:{cost:-3,time:-8,quality:-2,human:-2,risk:8}},
    {id:"ceo-balance",label:"Reequilibrar a operação",detail:"Reduzir a meta de automação até recuperar qualidade.",deltas:{cost:5,time:6,quality:7,human:8,risk:-7}}]},
  "Finanças":{question:"Onde ajustar o custo da operação?",context:"Modelos e revisão humana respondem por 71% do custo mensal.",choices:[
    {id:"fin-model",label:"Usar modelo menor na triagem",detail:"Reduz custo de API; exige nova avaliação de classificação.",deltas:{cost:-12,time:-5,quality:-3,human:3,risk:3}},
    {id:"fin-capacity",label:"Financiar capacidade humana temporária",detail:"Reduz fila e reabertura; aumenta custo do período.",deltas:{cost:14,time:-9,quality:5,human:-14,risk:-3}}]},
  "Marketing":{question:"Como tratar públicos com necessidades diferentes?",context:"O resultado médio esconde pior desempenho entre clientes de maior valor.",choices:[
    {id:"mkt-priority",label:"Priorizar clientes estratégicos",detail:"Melhora tempo desse grupo e atrasa os demais.",deltas:{cost:2,time:-3,quality:2,human:4,risk:2}},
    {id:"mkt-uniform",label:"Manter tratamento uniforme",detail:"Evita diferenciação, sem resolver o pior segmento.",deltas:{cost:0,time:0,quality:0,human:0,risk:0}}]},
  "Operações":{question:"Como reduzir a fila sem ocultar o problema?",context:"A fila humana opera acima de 92% da capacidade.",choices:[
    {id:"ops-priority",label:"Criar prioridade por consequência",detail:"Casos críticos passam primeiro; casos simples esperam mais.",deltas:{cost:1,time:-6,quality:4,human:-5,risk:-5}},
    {id:"ops-auto",label:"Aumentar decisão automática",detail:"Reduz fila rapidamente e eleva decisões não revisadas.",deltas:{cost:-8,time:-12,quality:-6,human:-12,risk:9}}]},
  "Tecnologia":{question:"Qual configuração técnica deve mudar?",context:"O agente de resolução concentra 46% do custo e 39% da latência.",choices:[
    {id:"tech-model",label:"Trocar o modelo de resolução",detail:"Modelo menor e mais rápido; precisa passar pelas avaliações da missão.",deltas:{cost:-15,time:-14,quality:-5,human:5,risk:4}},
    {id:"tech-cache",label:"Reutilizar evidências recentes",detail:"Reduz consultas; pode servir informação desatualizada.",deltas:{cost:-7,time:-11,quality:1,human:-1,risk:5}}]},
  "Compliance":{question:"Quando a decisão humana deve ser obrigatória?",context:"2,8% das respostas automatizadas não preservam todas as evidências usadas.",choices:[
    {id:"comp-gate",label:"Exigir evidência completa",detail:"Sem fonte registrada, o caso não pode ser automatizado.",deltas:{cost:9,time:10,quality:8,human:12,risk:-12}},
    {id:"comp-sample",label:"Auditar uma amostra maior",detail:"Aumenta detecção posterior sem bloquear o fluxo inteiro.",deltas:{cost:4,time:2,quality:4,human:5,risk:-5}}]},
  "Dados e IA":{question:"Como melhorar a qualidade dos agentes?",context:"As avaliações mostram queda em pedidos que combinam dois assuntos.",choices:[
    {id:"data-eval",label:"Adicionar avaliação por múltiplos assuntos",detail:"Bloqueia versões que não atingirem o patamar definido.",deltas:{cost:4,time:1,quality:9,human:-4,risk:-6}},
    {id:"data-context",label:"Ampliar o contexto enviado",detail:"Mais informação por execução; maior custo e exposição de dados.",deltas:{cost:10,time:7,quality:5,human:-3,risk:6}}]},
  "Segurança":{question:"Como reduzir a exposição a fornecedores externos?",context:"Dois agentes enviam contexto para APIs externas.",choices:[
    {id:"sec-private",label:"Migrar para endpoint privado",detail:"Reduz exposição e aumenta custo de infraestrutura.",deltas:{cost:13,time:3,quality:1,human:0,risk:-10}},
    {id:"sec-mask",label:"Mascarar dados antes do envio",detail:"Reduz exposição; pode retirar contexto útil.",deltas:{cost:4,time:5,quality:-2,human:2,risk:-7}}]},
  "Experiência do cliente":{question:"Quando oferecer contato humano?",context:"Clientes que reabrem duas vezes apresentam forte queda de satisfação.",choices:[
    {id:"cx-early",label:"Oferecer pessoa na segunda tentativa",detail:"Evita novas reaberturas e aumenta demanda humana.",deltas:{cost:11,time:-4,quality:8,human:14,risk:-4}},
    {id:"cx-self",label:"Manter automação até a terceira tentativa",detail:"Preserva capacidade; prolonga experiências malsucedidas.",deltas:{cost:-3,time:5,quality:-5,human:-4,risk:3}}]},
  "Gestão de pessoas":{question:"Como preparar a equipe para o trabalho que permaneceu humano?",context:"Os casos encaminhados são menos numerosos, porém mais complexos.",choices:[
    {id:"people-skill",label:"Treinar para exceções complexas",detail:"Eleva qualidade e custo no curto prazo.",deltas:{cost:8,time:3,quality:7,human:-5,risk:-4}},
    {id:"people-scale",label:"Aumentar equipe sem redesenhar funções",detail:"Expande capacidade rapidamente, com ganho limitado de qualidade.",deltas:{cost:15,time:-8,quality:2,human:-10,risk:-1}}]},
};

async function loadSession(code:string){const r=await fetch(`/api/session?code=${encodeURIComponent(code)}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);return j.state as Session}
async function saveSession(code:string,state:Session){const r=await fetch("/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,state})});const j=await r.json();if(!r.ok)throw new Error(j.error)}

export default function Home(){
  const [view,setView]=useState<View>("home");
  const [session,setSession]=useState<Session|null>(null);
  const [code,setCode]=useState("");
  const [name,setName]=useState("");
  const [profile,setProfile]=useState("");
  const [error,setError]=useState("");
  const [selectedMission,setSelectedMission]=useState("service");
  const [selectedAgent,setSelectedAgent]=useState<number|null>(null);
  const [facilitatorTab,setFacilitatorTab]=useState<"room"|"people"|"system">("room");
  const [selectedPerson,setSelectedPerson]=useState(0);

  useEffect(()=>{if(!code||!(view==="facilitator"||view==="participant"))return;const timer=setInterval(()=>loadSession(code).then(setSession).catch(()=>{}),1800);return()=>clearInterval(timer)},[code,view]);
  const mission=missions.find(m=>m.id===(session?.mission||selectedMission))||missions[0];

  async function createMission(){const next:Session={mission:selectedMission,phase:"lobby",participants:[],proposals:[],createdAt:new Date().toISOString()};const nextCode=`ORQ${Math.floor(100+Math.random()*900)}`;try{await saveSession(nextCode,next);setCode(nextCode);setSession(next);setView("facilitator")}catch(e){setError(e instanceof Error?e.message:"Não foi possível abrir a sala")}}
  async function join(){try{const current=await loadSession(code.toUpperCase());if(!name.trim()||!profile)throw new Error("Informe seu nome e escolha um perfil");if(current.participants.some(p=>p.profile===profile))throw new Error("Este perfil já foi ocupado");const next={...current,participants:[...current.participants,{name:name.trim(),profile}]};await saveSession(code.toUpperCase(),next);setCode(code.toUpperCase());setSession(next);setView("participant")}catch(e){setError(e instanceof Error?e.message:"Não foi possível entrar")}}
  async function update(next:Session){setSession(next);await saveSession(code,next)}

  if(view==="home")return <main className="landing"><div className="landing-brand"><span>O</span><b>ORQUESTRA LAB</b></div><section><p>LABORATÓRIO EXECUTIVO</p><h1>Entre numa operação conduzida por agentes de IA. Entenda, decida e veja as consequências.</h1><div className="entry-actions"><button onClick={()=>setView("catalog")}><small>VOU CONDUZIR A AULA</small><b>Entrar como facilitador</b><span>Escolha uma missão pronta e abra a sala →</span></button><button onClick={()=>setView("join")}><small>RECEBI UM CÓDIGO</small><b>Entrar como participante</b><span>Escolha um perfil disponível →</span></button></div></section></main>;

  if(view==="catalog")return <Shell title="Biblioteca de missões" back={()=>setView("home")}><div className="catalog-head"><p>ESCOLHA UMA EXPERIÊNCIA PRONTA</p><h1>Qual operação a turma vai governar?</h1><span>Agentes, regras, perfis, histórico e impactos já estão configurados.</span></div><div className="mission-cards">{missions.map((m,i)=><button key={m.id} className={selectedMission===m.id?"selected":""} onClick={()=>setSelectedMission(m.id)}><span>MISSÃO {String(i+1).padStart(2,"0")}</span><h2>{m.title}</h2><p>{m.summary}</p><dl><dt>Duração</dt><dd>{m.duration}</dd><dt>Conceitos</dt><dd>{m.concepts}</dd></dl><b>{selectedMission===m.id?"✓ Selecionada":"Selecionar missão"}</b></button>)}</div>{error&&<div className="error">{error}</div>}<button className="launch" onClick={createMission}>Abrir sala com “{missions.find(m=>m.id===selectedMission)?.title}” →</button></Shell>;

  if(view==="join")return <Shell title="Entrada do participante" back={()=>setView("home")}><div className="join-card"><p>ENTRAR NA SALA</p><h1>Use o código mostrado pelo facilitador.</h1><label>Código da sessão<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ORQ000" maxLength={6}/></label><button onClick={async()=>{try{const s=await loadSession(code);setSession(s);setError("")}catch(e){setError(e instanceof Error?e.message:"Sessão não encontrada")}}}>Consultar lugares disponíveis</button>{session&&<><label>Seu nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Como aparecerá na sala"/></label><div className="role-pick"><b>Escolha um perfil</b>{profiles.map(p=>{const taken=session.participants.some(x=>x.profile===p);return <button key={p} disabled={taken} className={profile===p?"selected":""} onClick={()=>setProfile(p)}>{p}<small>{taken?"ocupado":"disponível"}</small></button>})}</div><button className="join-now" onClick={join}>Ocupar este lugar →</button></>}{error&&<div className="error">{error}</div>}</div></Shell>;

  if(!session)return null;
  if(view==="participant")return <ParticipantScreen mission={mission} session={session} code={code} person={session.participants.find(p=>p.name===name)||{name,profile}} update={update}/>;
  return <Facilitator mission={mission} session={session} code={code} update={update} tab={facilitatorTab} setTab={setFacilitatorTab} selectedPerson={selectedPerson} setSelectedPerson={setSelectedPerson} selectedAgent={selectedAgent} setSelectedAgent={setSelectedAgent}/>;
}

function Shell({title,back,children}:{title:string;back:()=>void;children:React.ReactNode}){return <main className="shell"><header><button onClick={back}>←</button><b>ORQUESTRA LAB</b><span>{title}</span></header>{children}</main>}

function Facilitator({mission,session,code,update,tab,setTab,selectedPerson,setSelectedPerson,selectedAgent,setSelectedAgent}:{mission:any;session:Session;code:string;update:(s:Session)=>void;tab:string;setTab:(v:any)=>void;selectedPerson:number;setSelectedPerson:(n:number)=>void;selectedAgent:number|null;setSelectedAgent:(n:number|null)=>void}){
  const phases:Phase[]=["lobby","observe","decide","results"];
  const phaseLabels={lobby:"Entrada na sala",observe:"Observar 90 dias",decide:"Calibrar a operação",results:"Comparar resultados"};
  const current=phases.indexOf(session.phase);
  const outcomes=calculate(mission.metrics,session.proposals);
  return <main className="fac"><header><div><b>ORQUESTRA LAB</b><span>FACILITADOR · {mission.title}</span></div><div className="session-code"><small>CÓDIGO PARA ENTRAR</small><strong>{code}</strong></div><button disabled={current===3||(session.phase==="lobby"&&session.participants.length<1)} onClick={()=>update({...session,phase:phases[current+1]})}>{session.phase==="lobby"?"Iniciar experiência":session.phase==="observe"?"Abrir decisões":"Simular novo período"} →</button></header><div className="fac-body"><aside><p>ETAPA ATUAL</p><h1>{phaseLabels[session.phase]}</h1><span>{session.phase==="lobby"?"Aguarde as pessoas escolherem seus perfis.":session.phase==="observe"?"Explique o histórico e abra os agentes antes das decisões.":session.phase==="decide"?"Cada perfil recebe uma decisão diferente. Acompanhe as propostas.":"Compare os períodos e discuta o que cada mudança produziu."}</span><div className="phase-list">{phases.map((p,i)=><div className={session.phase===p?"active":current>i?"done":""} key={p}><i>{current>i?"✓":i+1}</i>{phaseLabels[p]}</div>)}</div></aside><section className="fac-main"><nav><button className={tab==="room"?"active":""} onClick={()=>setTab("room")}>Projeção da sala</button><button className={tab==="people"?"active":""} onClick={()=>setTab("people")}>Telas individuais <em>{session.participants.length}</em></button><button className={tab==="system"?"active":""} onClick={()=>setTab("system")}>Agentes por dentro</button></nav>{tab==="room"&&<Shared mission={mission} session={session} outcomes={outcomes}/>} {tab==="people"&&<People session={session} mission={mission} selected={selectedPerson} setSelected={setSelectedPerson}/>} {tab==="system"&&<System mission={mission} selected={selectedAgent} setSelected={setSelectedAgent}/>}</section></div></main>
}

function Shared({mission,session,outcomes}:{mission:any;session:Session;outcomes:number[]}){if(session.phase==="lobby")return <div className="waiting"><p>SALA ABERTA</p><h1>{mission.title}</h1><strong>{session.participants.length} de 10 pessoas conectadas</strong><div>{session.participants.map(p=><span key={p.name}>{p.name}<small>{p.profile}</small></span>)}</div></div>;if(session.phase==="observe")return <div className="shared"><p>RESULTADOS DOS ÚLTIMOS 90 DIAS</p><h1>{mission.title}</h1><h2>{mission.summary}</h2><Metrics values={mission.metrics}/><div className="shared-question">O resultado global melhorou. Por que alguns resultados começaram a se deteriorar?</div></div>;if(session.phase==="decide")return <div className="shared"><p>PROPOSTAS DA MESA</p><h1>{session.proposals.length} de {session.participants.length} decisões recebidas</h1><div className="proposal-board">{session.proposals.map(p=><article key={p.participant}><small>{p.profile} · {p.participant}</small><b>{p.label}</b><p>{p.reason||"Sem justificativa registrada."}</p></article>)}</div></div>;return <div className="shared"><p>NOVO PERÍODO SIMULADO</p><h1>O que mudou depois das decisões?</h1><div className="compare"><section><small>ANTES</small><Metrics values={mission.metrics}/></section><section><small>DEPOIS</small><Metrics values={outcomes}/></section></div><div className="shared-question">Não existe melhoria gratuita: quais decisões produziram ganhos e quais criaram novos riscos?</div></div>}

function Metrics({values}:{values:number[]}){const labels=["Resolução automática","Tempo médio","Reabertura","Carga da equipe humana","Custo mensal"];const suffix=["%"," min","%"," h/dia"," mil"];return <div className="metrics">{labels.map((l,i)=><article key={l}><span>{l}</span><b>{values[i].toFixed(i===4?0:1)}{suffix[i]}</b></article>)}</div>}

function People({session,mission,selected,setSelected}:{session:Session;mission:any;selected:number;setSelected:(n:number)=>void}){const p=session.participants[selected];return <div className="people"><div className="people-list">{session.participants.map((person,i)=><button className={selected===i?"active":""} onClick={()=>setSelected(i)} key={person.name}><span>{person.name.slice(0,2).toUpperCase()}</span><div><b>{person.name}</b><small>{person.profile}</small></div><em>{session.proposals.some(x=>x.participant===person.name)?"respondeu":"ver tela"}</em></button>)}</div><div className="phone-preview">{p?<ParticipantCard mission={mission} session={session} person={p} preview/>:<div className="empty">Nenhum participante conectado</div>}</div></div>}

function ParticipantScreen({mission,session,code,person,update}:{mission:any;session:Session;code:string;person:Participant;update:(s:Session)=>void}){return <main className="participant-app"><header><b>ORQUESTRA LAB</b><span>{person.name} · {person.profile}</span><small>Sessão {code}</small></header><ParticipantCard mission={mission} session={session} person={person} update={update}/></main>}

function ParticipantCard({mission,session,person,update,preview}:{mission:any;session:Session;person:Participant;update?:(s:Session)=>void;preview?:boolean}){const spec=decisions[person.profile];const existing=session.proposals.find(p=>p.participant===person.name);const [choice,setChoice]=useState(existing?.choice||"");const [reason,setReason]=useState(existing?.reason||"");if(session.phase==="lobby")return <div className={`participant-card ${preview?"preview":""}`}><p>VOCÊ ESTÁ CONECTADO</p><h1>{person.profile}</h1><span>A experiência começará quando o facilitador avançar. Seu perfil determina informações, controles e aprovações durante a missão.</span></div>;if(session.phase==="observe")return <div className={`participant-card ${preview?"preview":""}`}><p>OBSERVE PRIMEIRO</p><h1>Entenda a operação antes de modificá-la.</h1><span>{mission.summary}</span><div className="participant-note">Na tela da sala, abra os agentes e observe como modelos, ferramentas, regras e pessoas produzem esses resultados.</div></div>;if(session.phase==="results")return <div className={`participant-card ${preview?"preview":""}`}><p>RESULTADO COMPARTILHADO</p><h1>Sua decisão fez parte de uma nova configuração.</h1><span>{existing?`Você propôs: ${existing.label}.`:"Você não enviou uma proposta neste período."} Compare na projeção o efeito combinado de todas as decisões.</span></div>;if(!spec)return null;async function submit(){if(!choice||!update)return;const c=spec.choices.find(x=>x.id===choice)!;const proposal:Proposal={participant:person.name,profile:person.profile,choice,label:c.label,reason,deltas:c.deltas};const next={...session,proposals:[...session.proposals.filter(p=>p.participant!==person.name),proposal]};await update(next)}return <div className={`participant-card decision-card ${preview?"preview":""}`}><p>SUA DECISÃO · {person.profile.toUpperCase()}</p><h1>{spec.question}</h1><span>{spec.context}</span><div className="choices">{spec.choices.map(c=><button className={choice===c.id?"selected":""} onClick={()=>!preview&&setChoice(c.id)} key={c.id}><b>{c.label}</b><small>{c.detail}</small></button>)}</div><label>Justifique sua escolha<textarea value={reason} readOnly={preview} onChange={e=>setReason(e.target.value)} placeholder="Que resultado você protege e qual consequência aceita?"/></label>{!preview&&<button className="send" disabled={!choice} onClick={submit}>{existing?"Atualizar proposta":"Enviar proposta à mesa"} →</button>}{preview&&<div className="preview-note">O facilitador está vendo esta tela exata.</div>}</div>}

function System({mission,selected,setSelected}:{mission:any;selected:number|null;setSelected:(n:number|null)=>void}){const agents=mission.agents.length?mission.agents:missions[0].agents;return <div className="system"><header><p>ARQUITETURA DA MISSÃO</p><h1>Quatro agentes realizam trabalhos diferentes.</h1><span>O modelo é apenas uma peça do agente. Abra uma ficha para ver fornecedor, acesso, ferramentas e limite de autoridade.</span></header><div className="agent-grid">{agents.map((a:any,i:number)=><button onClick={()=>setSelected(i)} key={a.name}><small>AGENTE {i+1}</small><b>{a.name}</b><p>{a.job}</p><em>{a.provider} · {a.model}</em><u>Abrir ficha técnica →</u></button>)}</div>{selected!==null&&<div className="agent-sheet" onClick={()=>setSelected(null)}><article onClick={e=>e.stopPropagation()}><button onClick={()=>setSelected(null)}>×</button><p>FICHA TÉCNICA</p><h1>{agents[selected].name}</h1><h2>{agents[selected].job}</h2><dl><dt>Fornecedor</dt><dd>{agents[selected].provider}</dd><dt>Modelo e acesso</dt><dd>{agents[selected].model}</dd><dt>Ferramentas</dt><dd>{agents[selected].tools}</dd><dt>Limite de autoridade</dt><dd>{agents[selected].limit}</dd><dt>Instrução principal</dt><dd>Realize somente sua tarefa, use as fontes autorizadas, cite evidências e declare incerteza.</dd><dt>Tempo máximo</dt><dd>8 segundos por execução</dd></dl><div><b>O que acontece se trocar o modelo?</b><span>A simulação recalcula custo, tempo, qualidade avaliada, compatibilidade com ferramentas e exposição de dados.</span></div></article></div>}</div>}

function calculate(base:readonly number[],proposals:Proposal[]){const sum=proposals.reduce((a,p)=>({cost:a.cost+p.deltas.cost,time:a.time+p.deltas.time,quality:a.quality+p.deltas.quality,human:a.human+p.deltas.human,risk:a.risk+p.deltas.risk}),{cost:0,time:0,quality:0,human:0,risk:0});return [Math.max(45,Math.min(96,base[0]+sum.quality*.22-sum.risk*.08)),Math.max(5,base[1]*(1+sum.time/100)),Math.max(1,base[2]*(1-sum.quality/120+sum.risk/150)),Math.max(5,base[3]*(1+sum.human/100)),Math.max(120,base[4]*(1+sum.cost/100))]}
